<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExportOdersDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('export_order_details')->insert([
            [
                'id_export' => 1,
                'id_product' => 1,        // Sản phẩm 1
                'quantity' => 2,
                'price' => 75.25,
                'subtotal' => 150.50,
                'id_customer' => 'Customer A',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 2,
                'id_product' => 2,
                'quantity' => 1,
                'price' => 230.00,
                'subtotal' => 230.00,
                'id_customer' => 'Customer B',
                'id_user' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 3,
                'id_product' => 3,
                'quantity' => 5,
                'price' => 100.15,
                'subtotal' => 500.75,
                'id_customer' => 'Customer C',
                'id_user' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 4,
                'id_product' => 4,
                'quantity' => 4,
                'price' => 80.00,
                'subtotal' => 320.00,
                'id_customer' => 'Customer D',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 5,
                'id_product' => 5,
                'quantity' => 1,
                'price' => 100.99,
                'subtotal' => 100.99,
                'id_customer' => 'Customer E',
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 6,
                'id_product' => 6,
                'quantity' => 3,
                'price' => 250.00,
                'subtotal' => 750.00,
                'id_customer' => 'Customer F',
                'id_user' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 7,
                'id_product' => 7,
                'quantity' => 2,
                'price' => 210.15,
                'subtotal' => 420.30,
                'id_customer' => 'Customer G',
                'id_user' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 8,
                'id_product' => 8,
                'quantity' => 4,
                'price' => 70.10,
                'subtotal' => 280.40,
                'id_customer' => 'Customer H',
                'id_user' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 9,
                'id_product' => 9,
                'quantity' => 2,
                'price' => 305.10,
                'subtotal' => 610.20,
                'id_customer' => 'Customer I',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 10,
                'id_product' => 10,
                'quantity' => 2,
                'price' => 95.00,
                'subtotal' => 190.00,
                'id_customer' => 'Customer J',
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 11,
                'id_product' => 11,
                'quantity' => 4,
                'price' => 112.70,
                'subtotal' => 450.80,
                'id_customer' => 'Customer K',
                'id_user' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 12,
                'id_product' => 12,
                'quantity' => 2,
                'price' => 190.35,
                'subtotal' => 380.70,
                'id_customer' => 'Customer L',
                'id_user' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 13,
                'id_product' => 13,
                'quantity' => 2,
                'price' => 110.00,
                'subtotal' => 220.00,
                'id_customer' => 'Customer M',
                'id_user' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 14,
                'id_product' => 14,
                'quantity' => 3,
                'price' => 110.00,
                'subtotal' => 330.00,
                'id_customer' => 'Customer N',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 15,
                'id_product' => 15,
                'quantity' => 2,
                'price' => 70.25,
                'subtotal' => 140.50,
                'id_customer' => 'Customer O',
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
