<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ExportOrdersDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('export_order_details')->insert([
            [
                'id_export' => 1,
                'product_id' => 1,
                'quantity' => 2,
                'price' => 75.25,
                'subtotal' => 150000.50,
                'id_customer' => 'Customer A',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 2,
                'product_id' => 2,
                'quantity' => 1,
                'price' => 230.00,
                'subtotal' => 230000.00,
                'id_customer' => 'Customer B',
                'id_user' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 3,
                'product_id' => 3,
                'quantity' => 5,
                'price' => 100.15,
                'subtotal' => 500000.75,
                'id_customer' => 'Customer C',
                'id_user' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 4,
                'product_id' => 4,
                'quantity' => 4,
                'price' => 80.00,
                'subtotal' => 320000.00,
                'id_customer' => 'Customer D',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 5,
                'product_id' => 5,
                'quantity' => 1,
                'price' => 100.99,
                'subtotal' => 100000.99,
                'id_customer' => 'Customer E',
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 6,
                'product_id' => 6,
                'quantity' => 3,
                'price' => 250.00,
                'subtotal' => 750000.00,
                'id_customer' => 'Customer F',
                'id_user' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 7,
                'product_id' => 7,
                'quantity' => 2,
                'price' => 210.15,
                'subtotal' => 420000.30,
                'id_customer' => 'Customer G',
                'id_user' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 8,
                'product_id' => 8,
                'quantity' => 4,
                'price' => 70.10,
                'subtotal' => 280000.40,
                'id_customer' => 'Customer H',
                'id_user' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 9,
                'product_id' => 9,
                'quantity' => 2,
                'price' => 305.10,
                'subtotal' => 610000.20,
                'id_customer' => 'Customer I',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 10,
                'product_id' => 10,
                'quantity' => 2,
                'price' => 95.00,
                'subtotal' => 190000.00,
                'id_customer' => 'Customer J',
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 11,
                'product_id' => 11,
                'quantity' => 4,
                'price' => 112.70,
                'subtotal' => 450000.80,
                'id_customer' => 'Customer K',
                'id_user' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 12,
                'product_id' => 12,
                'quantity' => 2,
                'price' => 190.35,
                'subtotal' => 380000.70,
                'id_customer' => 'Customer L',
                'id_user' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 13,
                'product_id' => 13,
                'quantity' => 2,
                'price' => 110.00,
                'subtotal' => 220000.00,
                'id_customer' => 'Customer M',
                'id_user' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 14,
                'product_id' => 14,
                'quantity' => 3,
                'price' => 110.00,
                'subtotal' => 330000.00,
                'id_customer' => 'Customer N',
                'id_user' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 15,
                'product_id' => 15,
                'quantity' => 2,
                'price' => 70.25,
                'subtotal' => 140000.50,
                'id_customer' => 'Customer O',
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_export' => 16,
                'product_id' => 1,       
                'quantity' => 2,
                'price' => 150000,     
                'subtotal' => 2 * 150000,
                'id_customer' => 'Customer P',
                'id_user' => 1,
                'created_at' => Carbon::create(2024, 9, 12),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 17,
                'product_id' => 2,       
                'quantity' => 5,
                'price' => 250000,      
                'subtotal' => 5 * 250000,
                'id_customer' => 'Customer Q',
                'id_user' => 2,
                'created_at' => Carbon::create(2024, 10, 3),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 18,
                'product_id' => 3,      
                'quantity' => 10,
                'price' => 400000,       
                'subtotal' => 10 * 400000,
                'id_customer' => 'Customer R',
                'id_user' => 3,
                'created_at' => Carbon::create(2024, 11, 8),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 19,
                'product_id' => 4,       
                'quantity' => 4,
                'price' => 200000,      
                'subtotal' => 4 * 200000,
                'id_customer' => 'Customer S',
                'id_user' => 1,
                'created_at' => Carbon::create(2024, 12, 15),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 20,
                'product_id' => 5,     
                'quantity' => 1,
                'price' => 300000,      
                'subtotal' => 1 * 300000,
                'id_customer' => 'Customer T',
                'id_user' => 4,
                'created_at' => Carbon::create(2025, 1, 11),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 21,
                'product_id' => 6,     
                'quantity' => 15,
                'price' => 170000,      
                'subtotal' => 15 * 170000,
                'id_customer' => 'Customer U',
                'id_user' => 5,
                'created_at' => Carbon::create(2025, 2, 20),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 22,
                'product_id' => 7,       
                'quantity' => 6,
                'price' => 160000,      
                'subtotal' => 6 * 160000,
                'id_customer' => 'Customer V',
                'id_user' => 2,
                'created_at' => Carbon::create(2025, 3, 8),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 23,
                'product_id' => 8,      
                'quantity' => 8,
                'price' => 200000,       
                'subtotal' => 8 * 200000,
                'id_customer' => 'Customer W',
                'id_user' => 3,
                'created_at' => Carbon::create(2025, 4, 14),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 24,
                'product_id' => 9,       
                'quantity' => 10,
                'price' => 120000,       
                'subtotal' => 10 * 120000,
                'id_customer' => 'Customer X',
                'id_user' => 1,
                'created_at' => Carbon::create(2025, 5, 4),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_export' => 25,
                'product_id' => 10,    
                'quantity' => 5,
                'price' => 120000,      
                'subtotal' => 5 * 120000,
                'id_customer' => 'Customer Y',
                'id_user' => 4,
                'created_at' => Carbon::create(2025, 5, 21),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
